# uncomment and configure the monitor where the panel will start
# you can get monitor info using wlr-randr
#[monitor]
#width = 2560
#height = 1080
#name = "DP-1"

[dpms]
enabled = false
timeout_all = 3600
timeout_single = 1800

[bottom]
enabled = "True"
position = "BOTTOM"
Exclusive = "False"
size = 42

[views]
tilling = "True"
maximize_views_on_expo = "True"

[left]
enabled = "True"
position = "BOTTOM"
Exclusive = "False"
size = 64

[right]
position = "BOTTOM"
Exclusive = "False"
size = 42

[top]
menu_icon = "archlinux-logo"
folder_icon = "folder"
position = "TOP"
Exclusive = "True"
size = 12

[window_title_lenght]
size = 48

[top_background]
position = "BOTTOM"
Exclusive = "False"
size = 42

[change_icon_title]
firefoxdeveloperedition = "firefox-developer-edition"
gnome-terminal-server = "gnome-terminal"
codium-insiders-url-handler = "vscodium"
wlroots = "wayland"
com.obsproject.Studio = "com.obsproject.Studio"

[left_side_gestures]
right_click = "python /opt/waypanel/scripts/workspaces.py"
left_click = ""
middle_click = "kitty"

[center_side_gestures]
right_click = "python /opt/waypanel/scripts/workspaces.py"
left_click = ""
middle_click = "kitty"

[right_side_gestures]
right_click = "python /opt/waypanel/scripts/workspaces.py"
left_click = ""
middle_click = "kitty"
