[dpms]
enabled = false
timeout_all = 3600
timeout_single = 1800

[cmd]

[panel.bottom]
enabled = "True"
position = "BOTTOM"
Exclusive = "False"
size = "42"

[panel.left]
enabled = "True"
position = "BOTTOM"
Exclusive = "False"
size = "64"

[panel.right]
position = "BOTTOM"
Exclusive = "False"
size = "42"

[panel.top]
menu_icon = "archlinux-logo"
folder_icon = "folder"
bookmarks_icon = "librewolf"
clipboard_icon = "edit-paste"
soundcard_icon = "audio-volume-high"
system_icon = "system-shutdown"
bluetooth_icon = "bluetooth"
position = "TOP"
Exclusive = "True"
size = "12"
max_note_lenght = 100

[panel.top_background]
position = "BOTTOM"
Exclusive = "False"
size = "42"

[panel.views]
tilling = "True"
maximize_views_on_expo = "True"

[panel.window_title_lenght]
size = "48"

[panel.clipboard]
max_items = "100"

[panel.change_icon_title]
firefoxdeveloperedition = "firefox-developer-edition"
gnome-terminal-server = "gnome-terminal"
codium-insiders-url-handler = "vscodium"
wlroots = "wayland"
com = "{'obsproject': {'Studio': 'com.obsproject.Studio'}}"

[menu.icons]
Wayfire = "dialog-scripts"

[menu.VPN]
[[menu.VPN.item1]]
name = "Change Server"
cmd = "python /home/neo/.config/waypanel/scripts/mullvad-random-br.py"

[[menu.VPN.item2]]
name = "Connection Status"
cmd = "python /home/neo/.config/waypanel/scripts/mullvad-status.py"

[[menu.VPN.item3]]
name = "Mullvad Disconnect"
cmd = "python /home/neo/.config/waypanel/scripts/mullvad-disconnect.py"

[[menu.VPN.item4]]
name = "Mullvad Connect"
cmd = "python /home/neo/.config/waypanel/scripts/mullvad-connect.py"

[menu.Wayfire]
[[menu.Wayfire.item0]]
name = "Turn ON/OFF DP-2"
cmd = "python /home/neo/Scripts/wayfire/output_dp_2.py"

[[menu.Wayfire.item1]]
name = "test"
cmd = "test"

[[menu.Wayfire.item2]]
name = "Start Wayfire Debug"
cmd = "/home/neo/.local/wayfire/debug-build/bin/wayfire -d &>/tmp/wayfire-debug.log"

[[menu.Wayfire.item5]]
name = "Update Waypanel"
cmd = "cd /home/neo/Git/waypanel/ ; pip install .; notify-send waypanel updated!"

[folders.Home]
name = "Home"
path = "/home/my_home_user"
filemanager = "nautilus"
icon = "folder-home-symbolic"

[folders.Downloads]
name = "Downloads"
path = "Downloads"
filemanager = "nautilus"
icon = "folder-downloads-symbolic"

[folders.Documentos]
name = "Documentos"
path = "Documentos"
filemanager = "nautilus"
icon = "folder-documents-symbolic"

[folders.Imagens]
name = "Imagens"
path = "Imagens"
filemanager = "thunar"
icon = "folder-image-symbolic"

[folders.Waypanel]
name = "Waypanel Project"
path = "Git/waypanel"
filemanager = "kitty -- nvim ."
icon = "nvim"

[folders.Waypanel_Config]
name = ".Waypanel"
path = ".config/waypanel"
filemanager = "nautilus"
icon = "configuration_section-symbolic"

[folders.Compositor_Config]
name = ".Wayfire"
path = ".config/wayfire"
filemanager = "nautilus"
icon = "configuration_section-symbolic"

[dockbar.librewolf]
cmd = "librewolf"
icon = "librewolf"
wclass = "librewolf"
desktop_file = "librewolf"
name = "librewolf"
initial_title = "librewolf"

[dockbar.nautilus]
cmd = "nautilus --new-window"
icon = "nautilus"
wclass = "org.gnome.nautilus"
initial_title = "org.gnome.nautilus"
desktop_file = "org.gnome.Nautilus.desktop"
name = "Nautilus"

[dockbar.steam]
cmd = "mullvad-exclude gtk-launch steam.desktop"
icon = "steam"
wclass = "steam"
desktop_file = "steam.desktop"
name = "Steam"

[dockbar.hexchat]
cmd = "hexchat"
icon = "hexchat"
wclass = "hexchat"
desktop_file = "io.github.hexchat.desktop"
name = "Hexchat"

[dockbar.chromium]
cmd = "/usr/lib/chromium/chromium"
icon = "chromium"
wclass = "chromium"
desktop_file = "chromium.desktop"
name = "Chromium"

[launcher.notify_system]
cmd = "swaync-client -t"
icon = "notifyconf"

[launcher.separator]
cmd = "NULL"
icon = "gnome-panel-separator"
