[cmd]

[plugins]
list = "taskbar clock dockbar event_manager event_handler_decorator gestures_setup top_panel right_panel bottom_panel left_panel soundcard_menu system_monitor next_workspace_with_views volume_scroll bookmarks notes network_manager pacman bluetooth_manager clipboard_client clipboard_server notifier_client notify_server notify_watcher notify_client weather calendar calendar_notes mullvad scale_search scale_rules menu_setup places window_title app_launcher system_dashboard window_controls ai_prompt cripto"
disabled = "plugin_manager"
custom_path = "~/.config/waypanel/plugins"

[taskbar]
orientation = "h"
class_style = "taskbar-buttons"

[main_panel]
type = "top"

[dockbar_panel]
panel = "left-panel-center"

[window_title]
title_lenght = 50

[clipboard_server]
max_items = 100

[auto_fullscreen_app]
enabled = true
[[auto_fullscreen_app.items]]
app_id = "kitty"
title = "nvim!!"

[[auto_fullscreen_app.items]]
app_id = "Microsoft-edge"
title = "Max"

[plugins.clock]
position = "right"
priority = 1

[window_title.change_icon_title]
firefoxdeveloperedition = "firefox-developer-edition"
gnome-terminal-server = "gnome-terminal"
codium-insiders-url-handler = "vscodium"
wlroots = "wayland"
com = "{'obsproject': {'Studio': 'com.obsproject.Studio'}}"

[dockbar.nautilus]
cmd = "nautilus --new-window"
icon = "nautilus"
wclass = "org.gnome.nautilus"
initial_title = "org.gnome.nautilus"
desktop_file = "org.gnome.Nautilus.desktop"
name = "Nautilus"

[dockbar.firefox-developer-edition]
cmd = "firefox-developer-edition"
icon = "firefox-developer-edition"
wclass = "firefox-developer-edition"
desktop_file = "firefox-developer-edition"
name = "firefox-developer-edition"
initial_title = "firefox-developer-edition"

[dockbar.steam]
cmd = "mullvad-exclude gtk-launch steam.desktop"
icon = "steam"
wclass = "steam"
desktop_file = "steam.desktop"
name = "Steam"

[dockbar.hexchat]
cmd = "hexchat"
icon = "io.github.Hexchat"
wclass = "hexchat"
desktop_file = "io.github.hexchat.desktop"
name = "Hexchat"
initial_title = ""

[dockbar.chromium]
cmd = "chromium"
icon = "chromium"
wclass = "chromium"
desktop_file = "chromium"
name = "chromium"
initial_title = "chromium"

[dockbar.thunderbird]
cmd = "thunderbird"
icon = "thunderbird"
wclass = "thunderbird"
desktop_file = "thunderbird.desktop"
name = "Thunderbird"

[dockbar.cinny]
cmd = "cinny"
icon = "cinny"
wclass = "cinny"
desktop_file = "cinny"
name = "cinny"
initial_title = "cinny"

[panel.bottom]
enabled = true
position = "BOTTOM"
Exclusive = false
size = 42

[panel.left]
enabled = true
position = "BOTTOM"
Exclusive = false
size = 64

[panel.right]
enabled = true
position = "BOTTOM"
Exclusive = false
size = 42

[panel.top]
menu_icon = "archlinux-logo"
folder_icon = "folder"
bookmarks_icon = "internet-web-browser"
clipboard_icon = "edit-paste"
soundcard_icon = "audio-volume-high"
system_icon = "system-shutdown"
bluetooth_icon = "bluetooth"
notes_icon = "stock_notes"
notes_icon_delete = "delete"
position = "TOP"
Exclusive = true
size = 12
max_note_lenght = 100

[folders.Home]
name = "Home"
path = "/home/neo"
filemanager = "nautilus"
icon = "folder-home-symbolic"

[folders.Downloads]
name = "Downloads"
path = "Downloads"
filemanager = "nautilus"
icon = "folder-downloads-symbolic"

[launcher.separator]
cmd = "NULL"
icon = "gnome-panel-separator"

[notify.server]
show_messages = true
popup_position_x = 0
popup_position_y = 1
popup_width = 399
timeout = 10

[notify.client]
notification_icon_size = 64
body_max_width_chars = 80
popover_width = 500
popover_height = 600
max_notifications = 5

[custom_keybindings]
binding_terminal = "<ctrl><alt><super><shift> KEY_ENTER"
command_terminal = "alacritty"

[window_rules]
rule1 = 'on created if app_id is "testing_window_rule" then start_on_output "DP-1"'
