# waypanel.toml

## Monitor Configuration (uncomment and adjust)

## Power Management
[dpms]
enabled = false
timeout_all = 3600
timeout_single = 1800

## ======================
## Panel Configuration
## ======================
[panel]
[panel.bottom]
enabled = true
position = "BOTTOM"
Exclusive = false
size = 42

[panel.left]
enabled = true
position = "BOTTOM"
Exclusive = false
size = 64

[panel.right]
position = "BOTTOM"
Exclusive = false
size = 42

[panel.top]
menu_icon = "archlinux-logo"
folder_icon = "folder"
position = "TOP"
Exclusive = true
size = 12

[panel.top_background]
position = "BOTTOM"
Exclusive = false
size = 42

[panel.monitor]
name = "DP-1"
width = 1920
height = 1080

[panel.views]
tilling = true
maximize_views_on_expo = true

[panel.window_title_lenght]
size = 48

[panel.clipboard]
max_items = 50

[panel.change_icon_title]
firefoxdeveloperedition = "firefox-developer-edition"
gnome-terminal-server = "gnome-terminal"
codium-insiders-url-handler = "vscodium"
wlroots = "wayland"
com.obsproject.Studio = "com.obsproject.Studio"

## ======================
## Menu Configuration
## ======================
[menu]

## Icons for menu entries
[menu.icons]
# "System" = "system-shutdown-symbolic"
"Wayfire" = "dialog-scripts"

## VPN Submenu
[menu.VPN]
[[menu.VPN.item1]]
name = "Change Server"
cmd = "python /home/neo/.config/waypanel/scripts/mullvad-random-br.py"

[[menu.VPN.item2]]
name = "Connection Status"
cmd = "python /home/neo/.config/waypanel/scripts/mullvad-status.py"

[[menu.VPN.item3]]
name = "Mullvad Disconnect"
cmd = "python /home/neo/.config/waypanel/scripts/mullvad-disconnect.py"

[[menu.VPN.item4]]
name = "Mullvad Connect"
cmd = "python /home/neo/.config/waypanel/scripts/mullvad-connect.py"

## Wayfire Submenu
[menu.Wayfire]
[[menu.Wayfire.item0]]
name = "Turn ON/OFF DP-2"
cmd = "python /home/neo/Scripts/wayfire/output_dp_2.py"

[[menu.Wayfire.item1]]
name = "Patch wayfire and install"
cmd = "kitty -e bash -c \"cd ~/Git/wayfire/; ~/Scripts/wayfire/patch.apply; ~/Scripts/wayfire/install\""

[[menu.Wayfire.item2]]
name = "Start Wayfire Debug"
cmd = "/home/neo/.local/wayfire/debug-build/bin/wayfire -d &>/tmp/wayfire-debug.log"

[[menu.Wayfire.item5]]
name = "Update Waypanel"
cmd = "cd /home/neo/Git/waypanel/ ; pip install .; notify-send waypanel updated!"


## PIN Submenu (Commented Out)
# [menu.PIN]
#   [[menu.PIN.item1]]
#   name = "Pin Focused View"
#   cmd = "/opt/waypanel/scripts/mullvad-random-br.py"
#
#   [[menu.PIN.item2]]
#   name = "Unpin Focused View"
#   cmd = "python /home/neo/Git/pywayfire_examples/examples/set_view_as_wallpaper.py unpin"
#
#   [[menu.PIN.item3]]
#   name = "Set Focused As Wallpaper"
#   cmd = "python /home/neo/Git/pywayfire_examples/examples/set_view_as_wallpaper.py"
#
#

## Folder Shortcuts Configuration
[folders]
[folders.Home]
name = "Home"
path = "/home/my_home_user"
filemanager = "nautilus"
icon = "folder-home-symbolic"

[folders.Downloads]
name = "Downloads"
path = "Downloads"
filemanager = "nautilus"
icon = "folder-downloads-symbolic"

[folders.Documentos]
name = "Documentos"
path = "Documentos"
filemanager = "nautilus"
icon = "folder-documents-symbolic"

[folders.Imagens]
name = "Imagens"
path = "Imagens"
filemanager = "thunar"
icon = "folder-image-symbolic"

[folders.Waypanel]
name = "Waypanel Project"
path = "Git/waypanel"
filemanager = "kitty -- nvim ."
icon = "nvim"

[folders.Waypanel_Config]
name = ".Waypanel"
path = ".config/waypanel"
filemanager = "nautilus"
icon = "configuration_section-symbolic"

[folders.Compositor_Config]
name = ".Wayfire"
path = ".config/wayfire"
filemanager = "nautilus"
icon = "configuration_section-symbolic"

## ======================
## Dockbar Applications
## ======================
[dockbar]
[dockbar.firefox-developer-edition]
cmd = "/usr/lib/firefox-developer-edition/firefox"
icon = "firefox-developer-edition"
wclass = "firefoxdeveloperedition"
desktop_file = "firefoxdeveloperedition.desktop"
name = "Firefox Developer"

[dockbar.steam]
cmd = "mullvad-exclude gtk-launch steam.desktop"
icon = "steam"
wclass = "steam"
desktop_file = "steam.desktop"
name = "Steam"

[dockbar.code]
cmd = "codium-insiders"
icon = "vscodium"
wclass = "codium-insiders-url-handler"
desktop_file = "vscodium-insiders.desktop"
name = "Codium"

[dockbar.hexchat]
cmd = "hexchat"
icon = "hexchat"
wclass = "hexchat"
desktop_file = "io.github.hexchat.desktop"
name = "Hexchat"

[dockbar.chromium]
cmd = "/usr/lib/chromium/chromium"
icon = "chromium"
wclass = "chromium"
desktop_file = "chromium.desktop"
name = "Chromium"

[dockbar.nautilus]
cmd = "nautilus --new-window"
icon = "nautilus"
wclass = "org.gnome.nautilus"
initial_title = "org.gnome.nautilus"
desktop_file = "org.gnome.Nautilus.desktop"
name = "Nautilus"

[dockbar.thunderbird]
cmd = "thunderbird"
icon = "thunderbird"
wclass = "thunderbird"
desktop_file = "thunderbird.desktop"
name = "Thunderbird"


## Command Widgets Configuration
[cmd]
#[cmd.date]
#refresh = 1000000
#position = "center"
#cmd = "sh /home/neo/.config/hypr/scripts/weather.sh"
#css_class = "weather"

## ======================
## Launcher Configuration
## ======================
[launcher]

## Notification System Toggle
[launcher.notify_system]
cmd = "swaync-client -t"
icon = "notifyconf"

## Separator (Disabled)
[launcher.separator]
cmd = "NULL"
icon = "gnome-panel-separator"
