[workspace_9]
cmd = "wayctl --workspace set view focused 2 2"
icon = "9"

[workspace_8]
cmd = "wayctl --workspace set view focused 2 1"
icon = "8"

[workspace_7]
cmd = "wayctl --workspace set view focused 2 0"
icon = "7"

[workspace_6]
cmd = "wayctl --workspace set view focused 1 2"
icon = "6"


[workspace_5]
cmd = "wayctl --workspace set view focused 1 1"
icon = "5"

[workspace_4]
cmd = "wayctl --workspace set view focused 1 0"
icon = "4"

[workspace_3]
cmd = "wayctl --workspace set view focused 0 2"
icon = "3"

[workspace_2]
cmd = "wayctl --workspace set view focused 0 1"
icon = "2"

[workspace_1]
cmd = "wayctl --workspace set view focused 0 0"
icon = "1"
