[plugins]
list = "wayfire_config on_output_connect scale_exclusive taskbar clock dockbar color_picker move_view_to_empty_workspace screenshot event_manager event_handler_decorator gestures_setup top_panel right_panel bottom_panel left_panel fix_fullscreen_drag_drop swww system_monitor next_workspace_with_views screen_recorder volume_scroll soundcard_selector bookmarks bluetooth notes network_manager pacman clipboard_client clipboard_server wayfire_plugin_details wayfire_plugins notifier_client notify_server notify_watcher notify_client weather calendar mullvad scale_search scale_output_focus scale_fullscreen places window_title system_dashboard window_controls custom_menu appmenu"
disabled = ""

[clipboard_server]
log_enabled = false
max_items = 100
monitor_interval = 0.5

[notes]
notes_icon = "stock_notes"
notes_icon_delete = "edit-delete"

[clipboard_client]
popover_min_width = 500
popover_max_height = 600
thumbnail_size = 128
preview_text_length = 50
image_row_height = 60
text_row_height = 38
item_spacing = 5

[taskbar_panel]
panel = "bottom-panel"
exclusive_zone = true
width = 100

[taskbar]
icon_size = 32
spacing = 5
show_label = true
max_title_lenght = 25

[dockbar_content]
panel = "left-panel"
orientation = "v"
class_style = "dockbar-buttons"

[panel.primary_output]
output_name = "DP-1"

[panel.bottom]
enabled = 1.0
position = "BOTTOM"
Exclusive = 0.0
size = 42.0

[panel.left]
enabled = 1.0
position = "BOTTOM"
Exclusive = 0.0
size = 64.0

[panel.right]
enabled = 1.0
position = "BOTTOM"
Exclusive = 0.0
size = 42.0

[panel.top]
menu_icon = "archlinux-logo"
folder_icon = "folder"
bookmarks_icon = "internet-web-browser"
clipboard_icon = "edit-paste"
soundcard_icon = "audio-volume-high"
system_icon = "system-shutdown"
bluetooth_icon = "bluetooth"
notes_icon = "stock_notes"
notes_icon_delete = "delete"
position = "TOP"
Exclusive = 1.0
height = 32.0
size = 12.0
max_note_lenght = 100.0

[notify.client]
max_notifications = 5.0
body_max_width_chars = 80.0
notification_icon_size = 64.0
popover_width = 500.0
popover_height = 600.0

[notify.server]
show_messages = true

[dockbar_app.terminal]
cmd = "kitty"
icon = "utilities-terminal-symbolic"

[dockbar_app.file_manager]
cmd = "nautilus"
icon = "system-file-manager-symbolic"
