[firefox-developer-edition]
cmd = "/usr/lib/firefox-developer-edition/firefox"
icon = "firefox-developer-edition"
wclass = "firefoxdeveloperedition"
desktop_file = "firefoxdeveloperedition.desktop"
name = "Firefox Developer"

[steam]
cmd = "mullvad-exclude gtk-launch steam.desktop"
icon = "steam"
wclass = "steam"
desktop_file = "steam.desktop"
name = "Steam"

[code]
cmd = "codium-insiders"
icon = "vscodium"
wclass = "codium-insiders-url-handler"
desktop_file = "vscodium-insiders.desktop"
name = "Codium"

[telegram]
cmd = "telegram-desktop"
icon = "telegram-desktop"
wclass = "org.telegram.desktop"
desktop_file = "org.telegram.desktop.desktop"
name = "Telegram"

[hexchat]
cmd = "hexchat"
icon = "hexchat"
wclass = "hexchat"
desktop_file = "io.github.hexchat.desktop"
name = "Hexchat"

[chromium]
cmd = "/usr/lib/chromium/chromium"
icon = "chromium"
wclass = "chromium"
desktop_file = "chromium.desktop"
name = "Chromium"

[nautilus]
cmd = "nautilus --new-window"
icon = "nautilus"
wclass = "org.gnome.nautilus"
initial_title = "org.gnome.nautilus"
desktop_file = "org.gnome.Nautilus.desktop"
name = "Nautilus"

[thunderbird]
cmd = "thunderbird"
icon = "thunderbird"
wclass = "thunderbird"
desktop_file = "thunderbird.desktop"
name = "Thunderbird"

[chatgpt]
cmd = "gtk-launch chrome-fdaklkkpfdfonopeakobbnidhpebknjc-Default.desktop"
icon = "chrome-fdaklkkpfdfonopeakobbnidhpebknjc-Default"
wclass = "chromium"
initial_title = "chatgpt"
desktop_file = "chrome-fdaklkkpfdfonopeakobbnidhpebknjc-Default.desktop"
name = "Chatgpt"

[code-oss]
cmd = "code-oss"
icon = "code-oss"
wclass = "code-oss"
initial_title = "code-oss"
desktop_file = "code-oss.desktop"
name = "code-oss"
