[icons]
"System" = "system-shutdown-symbolic"


[[VPN.item_1]]
cmd = "/home/neo/Scripts/hyprland/mullvad-random-br.py"
name = "Change Server"

[[VPN.item_2]]
cmd = "/home/neo/Scripts/hyprland/mullvad-status.py"
name = "Connection Status"

[[VPN.item_3]]
cmd = "/home/neo/Scripts/hyprland/mullvad-disconnect.py"
name = "Mullvad Disconnect"

[[VPN.item_4]]
cmd = "/home/neo/Scripts/hyprland/mullvad-connect.py"
name = "Mullvad Connect"

[[System.item_1]]
cmd = "wayland-logout"
name = "Logout"
submenu = "Sair"

[[System.item_2]]
cmd = "reboot"
name = "Reiniciar"
submenu = "Sair"

[[System.shutdown_now]]
cmd = "shutdown -h now"
name = "Desligar PC"
submenu = "Sair"

[[System.item_6]]
cmd = "killall -9 waypanel.bin"
name = "Fechar Waypanel"
submenu = "Sair"

[[System.item_3]]
cmd = "hyprctl keyword monitor DP-1, disable"
name = "Desligar da direita"
submenu = "Monitores"

[[System.item_4]]
cmd = "hyprctl keyword monitor DP-2, disable"
name = "Desligar da esquerda  "
submenu = "Monitores"

[[System.item_5]]
cmd = "hyprctl reload"
name = "Religar"
submenu = "Monitores"
